local map = require('utils.map')

map.normal('j', 'gj')
map.normal('k', 'gk')
map.normal('Y', 'y$')
map.normal('Q', '@')
map.normal('n', 'nzz')
map.normal('N', 'Nzz')
map.normal('c*', '*``cgn')
map.normal('c#', '#``cgN')
map.normal('d*', '*``dgn')
map.normal('d#', '#``dgN')
map.normal('gQ', 'm`ggq``')
map.normal('g=', 'm`gg=G``')
map.normal('<f5>', '<cmd>luafile $XDG_CONFIG_HOME/nvim/init.lua<cr>')
map.normal('<f8>', '<cmd>source $VIMRUNTIME/syntax/hitest.vim<cr>')
map.normal('<bs>', '<c-^>', { noremap = true })
map.normal('<c-s>', '<cmd>write<cr>', { noremap = true })
map.normal('<c-h>', '<c-w>h', { noremap = true })
map.normal('<c-j>', '<c-w>j', { noremap = true })
map.normal('<c-k>', '<c-w>k', { noremap = true })
map.normal('<c-l>', '<c-w>l', { noremap = true })
map.normal('<up>', '<cmd>resize +5<cr>', { noremap = true })
map.normal('<down>', '<cmd>resize -5<cr>', { noremap = true })
map.normal('<left>', '<cmd>vertical resize -10<cr>', { noremap = true })
map.normal('<right>', '<cmd>vertical resize +10<cr>', { noremap = true })
map.normal('<c-w>t', '<cmd>tabe<cr>')
map.normal('<c-w>]', '<cmd>tabnext<cr>')
map.normal('<c-w>[', '<cmd>tabprev<cr>')
map.normal('<c-w>d', '<cmd>bwipe<cr>')
map.normal('<c-w>D', '<cmd>bwipe!<cr>')
map.normal('<c-w>Q', '<cmd>quit!<cr>')
map.normal('<c-w>C', '<cmd>close!<cr>')
