api.map.normal({
    { 'j', 'gj' },
    { 'k', 'gk' },
    { 'Q', '@' },
    { 'c*', '*``cgn' },
    { 'c#', '#``cgN' },
    { 'd*', '*``dgn' },
    { 'd#', '#``dgN' },
    { 'gQ', 'm`ggq``' },
    { 'g=', 'm`gg=G``' },
    { '<f5>', '<cmd>luafile $XDG_CONFIG_HOME/nvim/init.lua<cr>' },
    { '<f8>', '<cmd>source $VIMRUNTIME/syntax/hitest.vim<cr>' },
    { '<bs>', '<c-^>' },
    { '<c-s>', '<cmd>write<cr>' },
    { '<bs>', '<c-^>' },
    { '<c-s>', '<cmd>write<cr>' },
    { '<c-w>t', ':tabedit<cr>', { silent = true } },
    { '<c-w>Q', ':quit!<cr>', { silent = true } },
    { '<c-w>C', ':close!<cr>', { silent = true } },
    { '<c-w>d', ':bwipe<cr>', { silent = true } },
    { '<c-w>D', ':bwipe!<cr>', { silent = true } },
    { '<c-h>', '<c-w>h', { noremap = true } },
    { '<c-j>', '<c-w>j', { noremap = true } },
    { '<c-k>', '<c-w>k', { noremap = true } },
    { '<c-l>', '<c-w>l', { noremap = true } },
    { '<c-n>', 'gt', { noremap = true } },
    { '<c-p>', 'gT', { noremap = true } },
    { '<c-w>j', '<c-w>', { noremap = true } },
    { '<c-w>k', '<c-w>-', { noremap = true } },
    { '<c-w>h', '<c-w><', { noremap = true } },
    { '<c-w>l', '<c-w>>', { noremap = true } },

    {
        '<c-w>p',
        ':tabmove -" . v:count1 . "<cr>"',
        { expr = true, silent = true },
    },

    {
        '<c-w>n',
        ':tabmove +" . v:count1 . "<cr>"',
        { expr = true, silent = true },
    },
})
