api.set({
    mapleader = ' ',
    loaded_netrw = 0,
})

api.opt.set({
    completeopt = { 'menuone', 'noselect' },
    dictionary = '/usr/share/dict/words',
    expandtab = true,
    fillchars = { vert = ' ' },
    hidden = true,
    hlsearch = false,
    ignorecase = true,
    joinspaces = false,
    lazyredraw = true,
    list = true,
    laststatus = 2,
    listchars = { trail = '·', tab = '│ ' },
    mouse = 'n',
    number = true,
    relativenumber = true,
    scrolloff = 5,
    shiftwidth = 4,
    shortmess = api.opt.get('shortmess') + { c = true },
    showmode = false,
    signcolumn = 'yes:1',
    smartcase = true,
    smartindent = true,
    splitbelow = true,
    splitright = true,
    swapfile = false,
    tabstop = 4,
    tags = '.git/tags',
    undofile = true,
    wildignorecase = true,
    wrap = false,
})
