vim.api.nvim_set_keymap('n', 'j', 'gj', {})
vim.api.nvim_set_keymap('n', 'k', 'gk', {})
vim.api.nvim_set_keymap('n', 'n', 'nzzzv', {})
vim.api.nvim_set_keymap('n', 'N', 'Nzzzv', {})
vim.api.nvim_set_keymap('n', 'Y', 'y$', {})
vim.api.nvim_set_keymap('n', 'Q', '@q', {})
vim.api.nvim_set_keymap('n', 'H', '^', {})
vim.api.nvim_set_keymap('n', 'L', '$', {})
vim.api.nvim_set_keymap('n', 'c*', '*``cgn', {})
vim.api.nvim_set_keymap('n', 'c#', '#``cgN', {})
vim.api.nvim_set_keymap('n', 'd*', '*``dgn', {})
vim.api.nvim_set_keymap('n', 'd#', '#``dgN', {})
vim.api.nvim_set_keymap('n', 'g=', 'm`gg=G``', {})
vim.api.nvim_set_keymap('n', 'gQ', 'm`ggq``', {})
vim.api.nvim_set_keymap('n', '<bs>', '<c-^>', {})
vim.api.nvim_set_keymap('n', '<c-s>', ':write<cr>', {})
vim.api.nvim_set_keymap('n', '<c-h>', '<c-w>h', { noremap = true })
vim.api.nvim_set_keymap('n', '<c-j>', '<c-w>j', { noremap = true })
vim.api.nvim_set_keymap('n', '<c-k>', '<c-w>k', { noremap = true })
vim.api.nvim_set_keymap('n', '<c-l>', '<c-w>l', { noremap = true })
vim.api.nvim_set_keymap('n', '<c-w>d', ':bwipe<cr>', { silent = true })
vim.api.nvim_set_keymap('n', '<c-w>D', ':bwipe!<cr>', { silent = true })
vim.api.nvim_set_keymap('n', '<c-w>Q', ':quit!<cr>', { silent = true })
vim.api.nvim_set_keymap('n', '<c-w>C', ':close!<cr>', { silent = true })
vim.api.nvim_set_keymap('n', '<c-w>h', '10<c-w><', {})
vim.api.nvim_set_keymap('n', '<c-w>j', '5<c-w>+', {})
vim.api.nvim_set_keymap('n', '<c-w>k', '5<c-w>-', {})
vim.api.nvim_set_keymap('n', '<c-w>l', '10<c-w>>', {})
vim.api.nvim_set_keymap('n', '\\', ':term<cr>', { silent = true });
vim.api.nvim_set_keymap('n', '\\s', ':split | term<cr>', { silent = true });
vim.api.nvim_set_keymap('n', '\\v', ':vsplit | term<cr>', { silent = true });
