vim.api.nvim_set_keymap('n', 'j', 'gj', { noremap = true })
vim.api.nvim_set_keymap('n', 'k', 'gk', { noremap = true })
vim.api.nvim_set_keymap('n', 'Y', 'y$', { noremap = true })
vim.api.nvim_set_keymap('n', 'gj', 'j', { noremap = true })
vim.api.nvim_set_keymap('n', 'gk', 'k', { noremap = true })
vim.api.nvim_set_keymap('n', 'c*', '*``cgn', { noremap = true })
vim.api.nvim_set_keymap('n', 'c#', '#``cgN', { noremap = true })
vim.api.nvim_set_keymap('n', 'd*', '*``dgn', { noremap = true })
vim.api.nvim_set_keymap('n', 'd#', '#``dgN', { noremap = true })
vim.api.nvim_set_keymap('n', '<bs>', '<c-^>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<c-w><bs>', '<cmd>bwipe<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', '<c-s>', '<cmd>write<cr>', { noremap = true })
